name: scrollable_positioned_list_extended
version: 0.3.8
description: > 
  scrollable_positioned_list with helper methods like scrollToMax,scrollToMin,jumpToMax and jumToMin.

homepage : https://pub.dev/packages/scrollable_positioned_list_extended
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: 'flutter'
  collection: ^1.15.0
  scroll_to_index: ^3.0.1

dev_dependencies:
  pedantic: ^1.10.0-0
  flutter_test:
    sdk: 'flutter'
  